### ISSUE TITLE
Can you provide a training dataset?

### ISSUE THREAD

**Issue by 980202006** [ChenPaulYu/DJtransGAN#1]
This work is very attractive. Can I ask for a data set to try to reproduce the model of the paper, and make sure it is only used for academic research and not for commercial use?

**Comment by ChenPaulYu** [comment]
Hi, thanks for your asking. I am sorry that I can not provide the training data due to license issues. I just released the code of the data generation pipeline here (https://github.com/ChenPaulYu/DJtransGAN-dg-pipeline) and a pre-trained model for you to try on. I hope it is helpful for you 😊.

**Comment by 980202006** [comment]
Thank you!

**Comment by MiniXC** [comment]
I cannot find the pre-trained model, I might be looking in the wrong place though... Did you end up releasing it?
Edit: just found your download utility, no need to reopen this!
